---
bridge_interface: "docker0"
instances:
  ttylinux:
    boot_source:
      kernel_image_path: "/home/john/.config/firecracker/ttylinux/vmlinux"
      boot_args: "console=ttyS0 reboot=k panic=1 pci=off enet nofirewall"
    drives:
      rootfs:
        drive_id: "rootfs"
        path_on_host: "/home/john/.config/firecracker/ttylinux/ubuntu-22.04.ext4"
        is_root_device: true
        is_read_only: false
    machine_config:
      vcpu_count: 1
      mem_size_mib: 512
    network_interfaces:
      - iface_id: eth0
        # /usr/local/bin/fcnet-setup.sh will set the IP to 172.17.0.2/30
        guest_mac: "06:00:ac:11:00:02"
