---
bridge_interface: "virbr0"
tap_interface: "ftap0"
instances:
  - name: ttylinux
    boot_source:
      kernel_image_path: "/home/guru/Programs/firecracker/ttylinux/vmlinux"
      boot_args: "ramdisk_size=98304 root=/dev/ram0 ro console=ttyS0 reboot=k panic=1 pci=off enet nofirewall"
      initrd_path: "/home/guru/Programs/firecracker/ttylinux/filesys.gz"
