---
- name: "{{instance_item.key}}: Start Firecracker console"
  systemd:
    state: started
    name: "firecracker-console@{{instance_item.key}}"
    scope: user
  tags: [ create ]

- name: "{{instance_item.key}}: Start Firecracker service"
  systemd:
    state: started
    name: "firecracker@{{instance_item.key}}"
    scope: user
  tags: [ create ]

- name: "{{instance_item.key}}: Set socket fact"
  set_fact:
    instance_socket: "{{firecracker_runpath}}/firecracker-{{instance_item.key}}.socket"
  tags: [ create ]

- name: "{{instance_item.key}}: Configuring Boot Source"
  uri:
    url: http://localhost/boot-source
    method: PUT
    unix_socket: "{{instance_socket}}"
    body: "{{instance_item.value['boot_source']|to_json}}"
    status_code:
      - 200
      - 204
    body_format: json
  tags: [ create ]

- name: "{{instance_item.key}}: Configuring Root Source"
  uri:
    url: http://localhost/drives/rootfs
    method: PUT
    unix_socket: "{{instance_socket}}"
    body: "{{instance_item.value['drives']['rootfs']|to_json}}"
    status_code:
      - 200
      - 204
    body_format: json
  tags: [ create ]

- name: "{{instance_item.key}}: Configuring Machine"
  uri:
    url: http://localhost/machine-config
    method: PUT
    unix_socket: "{{instance_socket}}"
    body: "{{instance_item.value['machine_config']|to_json}}"
    status_code:
      - 200
      - 204
    body_format: json
  when: instance_item.value['machine_config'] is defined
  tags: [ create ]

- name: "{{instance_item.key}}: Configuring Networking"
  uri:
    url: "http://localhost/network-interfaces/{{item.iface_id}}"
    method: PUT
    unix_socket: "{{instance_socket}}"
    body: "{{item|to_json}}"
    status_code:
      - 200
      - 204
    body_format: json
  loop: "{{instance_item.value['network_interfaces']}}"
  when: instance_item.value['network_interfaces'] is defined
  tags: [ create ]

- name: "{{instance_item.key}}: Start instance"
  uri:
    url: http://localhost/actions
    method: PUT
    unix_socket: "{{instance_socket}}"
    body: '{"action_type": "InstanceStart"}'
    status_code:
      - 200
      - 204
    body_format: json
  tags: [ create ]
