- name: "{{instance_item.key}}: Create Tap interface"
  shell: "{{iputil_cmd}} tuntap add dev {{item.host_dev_name}} mode tap user {{ansible_user_id}}"
  args:
    creates: "/proc/sys/net/ipv4/conf/{{item.host_dev_name}}"
  become: true
  loop: "{{instance_item.value['network_interfaces']}}"
  tags: [ create_interfaces ]

- name: "{{instance_item.key}}: Add Tap interface to bridge"
  shell: "{{iputil_cmd}} link set {{item.host_dev_name}} master {{bridge_interface}}"
  become: true
  loop: "{{instance_item.value['network_interfaces']}}"
  tags: [ create_interfaces ]

- name: "{{instance_item.key}}: Set Tap interface up"
  shell: "{{iputil_cmd}} link set dev {{item.host_dev_name}} up"
  become: true
  loop: "{{instance_item.value['network_interfaces']}}"
  tags: [ create_interfaces ]
