- name: Add tap
  shell: "{{iputil_cmd}} tuntap add dev fc-{{(item.name|hash('md5'))[0:8]}} mode tap user {{ansible_user_id}}"
  args:
    creates: "/proc/sys/net/ipv4/conf/fc-{{(item.name|hash('md5'))[0:8]}}"
  become: true

- name: Add tap bridge
  shell: "{{iputil_cmd}} link set fc-{{(item.name|hash('md5'))[0:8]}} master {{bridge_interface}}"
  become: true

- name: Bridge up
  shell: "{{iputil_cmd}} link set dev {{item}} up"
  become: true
  with_items:
    - "{{bridge_interface}}"
    - "fc-{{(item.name|hash('md5'))[0:8]}}"
